name: Speedlify — scan & publish

on:
  schedule:
    - cron: "0,30 8-18 8-14 11 *"  # Du 8 au 14 de novembre, toutes les 30 minutes entre 9h et 19h
  workflow_dispatch: {}

permissions:
  contents: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install npm dependencies
        run: npm install

      - name: Install chrome
        uses: browser-actions/setup-chrome@v2
        id: setup-chrome

      # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
      - name: Disable AppArmor user namespace restrictions
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Git identity for CI
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x scripts/run-publish.sh

      - name: Run publish script
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROME_DEVEL_SANDBOX: /usr/local/sbin/chrome-devel-sandbox
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          cd scripts
          ./run-publish.sh
