name: Speedlify — scan & publish

on:
  schedule:
    # The action is triggered periodically “At 20:00 on Monday.” (https://crontab.guru/#0_20_*_*_1)
    - cron: "0 20 * * 1"
  # Allows the action to be triggered manually from GitHub "Actions" tab
  workflow_dispatch: { }

permissions:
  contents: write
  # Allows other GH actions to be triggered when this one finishes
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install npm dependencies
        run: npm install

      - name: Install chrome
        uses: browser-actions/setup-chrome@v2
        id: setup-chrome

      # https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
      - name: Disable AppArmor user namespace restrictions
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Git identity for CI
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Make script executable
        run: chmod +x scripts/run-publish.sh

      - name: Run publish script
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROME_DEVEL_SANDBOX: /usr/local/sbin/chrome-devel-sandbox
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          cd scripts
          ./run-publish.sh
